### PR TITLE
Make it go gettable

### PR DESCRIPTION
**Pull request by dolanor**
Hi,

I started making this, then I thought I should have opened an issue about it to see your point of view. But then, I was nearly finished, so I figured I might as well send a PR already…

## What it does

* it makes the package/app go gettable by using full named package (with the github.com prefix) in imports
* It removes the need for a dependency file, since go will handle it itself through go get
* It removes the need for special locally defined GOPATH with the use of full package name

Tell me what you think.

### CODE REVIEW

**Comment by jwriteclub** [comment]
Hi @dolanor thanks a lot for this. We had our reasons for the current setup, but we've recently been thinking in this direction. Many thanks for doing this re-factor.

**Comment by dolanor** [comment]
You're welcome.
Can you share what were your need to set it up like that? I've seen it multiple time, and except for not being "connected" to github, I didn't see the point. So I guess I might be short sighted. But I really would like to know.

**Comment by jwriteclub** [comment]
@dolanor due to the restrictions of gomobile (the bindings for android/iOS), we found it convenient to use a "monorepo" for the go code for the mobile portions of our browser. At the same time, when we started using go, there was not a consensus for dependency management, as has now emerged in the go ecosystem with the upcoming `go dep`. We were constantly running into issues with conflicting deps and developers who were losing time to messing with the go environment setup, so we started creating a separate GOPATH for each monorepo. Thus, for development we were checking out complete GOPATHs and not just the individual components. When we broke this code out into it's own project, we just continued with our normal technique.

As part of opening up Tenta DNS and switching to a fully public development module for this codebase, we actually planned to make this switch at some point. But all of our developers are used to our current layout, so momentum continued.

**Comment by dolanor** [comment]
I battled with gomobile and deps/vendoring too… Thanks for the details.
And with that new merge, it doesn't impact gomobile build?

**Pull request merged**
