### PR TITLE
Clean up stressor.go

### PR DESCRIPTION
**Pull request by mesartwell**
Generally just trying to increase code readability by reducing indentation level and using a standard worker-pool structure.

### CODE REVIEW

**Comment by mesartwell** [comment]
Note: not sure why CI build fails. I ran launched travis against my fork'd repo and it completed okay.

**Comment by jwriteclub** [comment]
Thanks a lot for your contribution!

It looks like one of the travis workers timed out for unknown reasons. Rerunning the build shows this PR as passing.

However, I noticed that you removed the "version" variable and the ability to have the binary print out it's version. Please restore this, it's very useful to be able to ask a binary to list it's exact version.

Also, please confirm (via a comment on this PR or an email to hello@tenta.io) that you're making these contributions under the Apache 2 license.

**Comment by mesartwell** [comment]
I've added the version bit back.

I confirm these contributions are made under the Apache 2 license.

**Review by jwriteclub — APPROVED** [review]

**Comment by jwriteclub** [comment]
Thanks a lot for your contribution @mesartwell

**Pull request merged**
